backend:
  name: git-gateway
  branch: main
media_folder: "_site/photo-images"
public_folder: "/photo-images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "/blog"        # points to your blog directory
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "article.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"],
         options: ["post", "Featured"]}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image Caption", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
